# logging.level.org.springframework.security=DEBUG

logging:
    level:
        org:
            springframework:
                # security: DEBUG

spring:
    application:
        name: richis_app
    datasource:
        url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimezone=UTC
        username: bestuser
        password: OE&r5nk4
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        database: mysql
        show-sql: false
    flyway:
        baseline-on-migrate: true
    thymeleaf:
        encoding: utf-8
    servlet:
        multipart: 
            max-file-size: 64MB
            max-request-size: 64MB
            enabled: true
    devtools:
        restart:
            additional-paths: src/main/resources
            exclude: files/**,logs/**
    messages:
        basename: lang/messages
    data:
        redis:
            port: 6379
            host: localhost

server:
    port: 8081
    servlet:
        session:
            timeout: 3600